.TH QLIX2 "1" "July 2008" linux " "User Manuals"
.SH NAME
qlix2 \- Manage MTP devices
.SH SYNOPSIS
.B qlix2 
[\fIOPTION\fR]...
.SH DESCRIPTION
Qlix is a user interface that allows users to manage MTP devices. It strives
to leave the smallest possible memory footprint with the fewest possible 
dependencies, while being easy and intuative to use.
.SH OPTIONS
--FixBadPlaylists will attempt to automatically fix bad playlists that hold
  incorrect track information
--FixBadAlbums will attempt to automatically fix bad albums that hold
  incorrect track information
--SimulateTransfers use this to test Qlix functionality and report bugs. It
  only communicates with the device to create a layout of the device in the 
  program that the user can then interact with, without making any permanent
  changes to the device's file system
